#指定当前环境使用的配置文件
# application-dev.yml:表示开发时使用的配置文件
# application-prd.yml:表示上线时使用的配置文件
spring:
 profiles:
  active: prd    #即application-prd.yml中的“prd”,不能写成application-prd.yml

##设置debug模式
#debug: true
##设置上下文路径
#server:
#  servlet:
#    path: /springbootdemo
##设置日志文件位置
## 设置日志的级别（最低打印哪个级别的日志）
#logging:
#  file: e:/springboottest1.log
#  level:
#   root: info
##设置数据库
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    name: root
#    password: root
##自定义配置项
#shopping-mall:
# config:
#  name: 原滋原味
#  description: 这是一家专注于农家土特产的购物商城
#  hot-sales: 20
#  show-advertise: true